# __TelecomX: Modelos de Prediccion__

# __Analisis y preparacion de los datos__

## __Objetivo__

- Preparar los datos (limpieza, codificacion y normalizacion).
- Realizar analisis de correlacion y seleccion de variables.

## __Importar Librerias__

In [1]:
import numpy as np
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import LinearSegmentedColormap

# version de las libreria utilizadas
print(f'numpy=={np.__version__}')
print(f'pandas=={pd.__version__}')
print(f'matplotlib=={matplotlib.__version__}')
print(f'seaborn=={sns.__version__}')

numpy==2.2.6
pandas==2.3.1
matplotlib==3.10.3
seaborn==0.13.2

## __Importar datos__

In [2]:
# cargar datos preprocesados desde GitHub
data = pd.read_csv('https://raw.githubusercontent.com/jbernalg/challenge_TelecomX/refs/heads/main/data_out/datos_tratados.csv', sep=',')
data.head()

,cancelacion,genero,jubilado,en_pareja,dependientes,meses_contrato,servicio_telefonico,multiples_lineas,servicio_internet,seguridad_online,...,proteccion_dispositivo,soporte_efectivo,streaming_TV,streaming_peliculas,tipo_contrato,facturacion_electronica,metodo_pago,cuenta_mensual,cuentas_total,cuentas_diarias
0,0,Femenino,No,Si,Si,9,Si,No,DSL,No,...,No,Si,Si,No,un year,Si,cheque por correo,65.6,593.30,0.242963
1,0,Masculino,No,No,No,9,Si,Si,DSL,No,...,No,No,No,Si,mes a mes,No,cheque por correo,59.9,542.40,0.221852
2,1,Masculino,No,No,No,4,Si,No,Fibra_optica,No,...,Si,No,No,No,mes a mes,Si,cheque electronico,73.9,280.85,0.615833
3,1,Masculino,Si,Si,No,13,Si,No,Fibra_optica,No,...,Si,No,Si,Si,mes a mes,Si,cheque electronico,98.0,1237.85,0.251282
4,1,Femenino,Si,Si,No,3,Si,No,Fibra_optica,No,...,No,Si,Si,No,mes a mes,Si,cheque por correo,83.9,267.40,0.932222

> Eliminar _cuentas_diarias_ debido a que fue obtenida a partir de _cuenta_mensual_. Es informacion redundante.

In [3]:
datos = data.drop(['cuentas_diarias'], axis=1)
datos.head()

,cancelacion,genero,jubilado,en_pareja,dependientes,meses_contrato,servicio_telefonico,multiples_lineas,servicio_internet,seguridad_online,respaldo_online,proteccion_dispositivo,soporte_efectivo,streaming_TV,streaming_peliculas,tipo_contrato,facturacion_electronica,metodo_pago,cuenta_mensual,cuentas_total
0,0,Femenino,No,Si,Si,9,Si,No,DSL,No,Si,No,Si,Si,No,un year,Si,cheque por correo,65.6,593.30
1,0,Masculino,No,No,No,9,Si,Si,DSL,No,No,No,No,No,Si,mes a mes,No,cheque por correo,59.9,542.40
2,1,Masculino,No,No,No,4,Si,No,Fibra_optica,No,No,Si,No,No,No,mes a mes,Si,cheque electronico,73.9,280.85
3,1,Masculino,Si,Si,No,13,Si,No,Fibra_optica,No,Si,Si,No,Si,Si,mes a mes,Si,cheque electronico,98.0,1237.85
4,1,Femenino,Si,Si,No,3,Si,No,Fibra_optica,No,No,No,Si,Si,No,mes a mes,Si,cheque por correo,83.9,267.40

## __Resumen estadistico__

In [4]:
# resumen estadistico de las variables numericas
datos.describe()

       cancelacion  meses_contrato  cuenta_mensual  cuentas_total
count  7032.000000     7032.000000     7032.000000    7032.000000
mean      0.265785       32.421786       64.798208    2283.300441
std       0.441782       24.545260       30.085974    2266.771362
min       0.000000        1.000000       18.250000      18.800000
25%       0.000000        9.000000       35.587500     401.450000
50%       0.000000       29.000000       70.350000    1397.475000
75%       1.000000       55.000000       89.862500    3794.737500
max       1.000000       72.000000      118.750000    8684.800000

In [5]:
# informacion de todas las variables
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cancelacion              7032 non-null   int64
 1   genero                   7032 non-null   object
 2   jubilado                 7032 non-null   object
 3   en_pareja                7032 non-null   object
 4   dependientes             7032 non-null   object
 5   meses_contrato           7032 non-null   int64
 6   servicio_telefonico      7032 non-null   object
 7   multiples_lineas         7032 non-null   object
 8   servicio_internet        7032 non-null   object
 9   seguridad_online         7032 non-null   object
 10  respaldo_online          7032 non-null   object
 11  proteccion_dispositivo   7032 non-null   object
 12  soporte_efectivo         7032 non-null   object
 13  streaming_TV             7032 non-null   object
 14  streaming_peliculas      7032 non-null   object
 15  tipo_contrato            7032 non-null   object
 16  facturacion_electronica  7032 non-null   object
 17  metodo_pago              7032 non-null   object
 18  cuenta_mensual           7032 non-null   float64
 19  cuentas_total            7032 non-null   float64
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB